version: "3.9"
services:
  redis:
    image: "redis:alpine"
    container_name: redis_queue
    restart: always
  stream_generator:
    build: .
    container_name: stream_generator
    environment:
      - REDIS_HOST=redis_queue
    depends_on:
      - redis
    volumes:
      - <enter-data-dir-path>:/main_data_bucket
    restart: always
    command: python /src/stream_generator/generator.py
  stream_processor:
    build: .
    container_name: stream_processor
    environment:
      - REDIS_HOST=redis_queue
    depends_on:
      - redis
    restart: always
    command: python /src/stream_processor/processor.py
  monitoring:
    build: .
    container_name: queue_monitor
    environment:
      - REDIS_HOST=redis_queue
    depends_on:
      - redis
    restart: always
    command: python /src/queue_monitor/monitoring.py
